name: Publish package on release

on:
  release:
    types: [created]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - run: npm --no-git-tag-version version ${{github.ref_name}}
        working-directory: ./Assets/EZUtils/EZFXLayer
      - run: npm publish
        working-directory: ./Assets/EZUtils/EZFXLayer
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      