name: Create releases for updated packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    strategy:
      # an awkward consequence is that dependencies might not get published
      # but nothing to do about that in a workflow
      fail-fast: false
      matrix:
        package:
          - name: com.timiz0r.ezutils.ezfxlayer
            path: ./src/EZFXLayer
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup npmrc
        run: |
          cat <<EOF > ~/.npmrc
          //pkgs.dev.azure.com/timiz0r/EZUtils/_packaging/EZUtils/npm/registry/:username=timiz0r
          //pkgs.dev.azure.com/timiz0r/EZUtils/_packaging/EZUtils/npm/registry/:_password=\${AZURE_ARTIFACTS_PAT}
          //pkgs.dev.azure.com/timiz0r/EZUtils/_packaging/EZUtils/npm/registry/:email=foo@foo.foo
          registry=https://pkgs.dev.azure.com/timiz0r/EZUtils/_packaging/EZUtils/npm/registry/
          always-auth=true
          EOF
      - name: Publish package
        uses: ./.github/actions/publish-package
        with:
          package-path: ${{ matrix.package.path }}
        env:
            AZURE_ARTIFACTS_PAT: ${{secrets.AZURE_ARTIFACTS_PAT}}
